openapi: 3.0.1
info:
  title: API Demo
  version: "1.0"
servers:
- url: http://110.42.103.198:22440/v1
paths:
  /patent/trend1:
    post:
      summary: 专利趋势1
      operationId: patent_trend1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trend1Req'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trend1Res'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/trend2:
    post:
      summary: 专利趋势2
      operationId: patent_trend2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trend2Req'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trend2Res'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/applicant:
    post:
      summary: 申请人分析
      operationId: patent_applicant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicantReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicantRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/area:
    post:
      summary: 地域分析
      operationId: patent_area
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AreaReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AreaRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/type:
    post:
      summary: 地域分析
      operationId: patent_type
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TypeReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TypeRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent_report/save:
    post:
      summary: 报告保存
      operationId: patent_report_save
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatentReportReq'
        required: true
      responses:
        "200":
          description: success
          content: {}
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent_report_detail/save:
    post:
      summary: 报告详情保存
      operationId: patent_report_detail_save
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatentReportDetailReq'
        required: true
      responses:
        "200":
          description: success
          content: {}
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Trend1Req:
      type: object
      properties:
        industry:
          type: string
        area:
          type: string
    Trend1Res:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Trend1Res_data'
      example:
        data:
          year: year
          num: 0
    Trend2Req:
      type: object
      properties:
        industry:
          type: string
        area:
          type: string
    Trend2Res:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Trend2Res_data'
      example:
        data:
          proportion: 1.4658129
          year: year
          apply_num: 6
          authorization_num: 0
    ApplicantReq:
      type: object
      properties:
        industry:
          type: string
        area:
          type: string
    ApplicantRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ApplicantRes_data'
      example:
        data:
          num: 0
          applicant: applicant
    AreaReq:
      type: object
      properties:
        industry:
          type: string
    AreaRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/AreaRes_data'
      example:
        data:
          area: area
          year: year
          num: 0
    TypeReq:
      type: object
      properties:
        industry:
          type: string
    TypeRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/TypeRes_data'
      example:
        data:
          num: 0
          type: type
    PatentReportReq:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: string
        title:
          type: string
        batch_id:
          type: string
    PatentReportRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/PatentReportRes_data'
      example:
        data:
          id: 0
    PatentReportRes_data:
      type: object
      properties:
        id:
          type: integer
      example:
        id: 0
    PatentReportDetailReq:
      type: object
      properties:
        id:
          type: integer
        report_id:
          type: integer
        type:
          type: string
        sub_title:
          type: string
        content:
          type: string
        data:
          type: string
    PatentReportDetailRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/PatentReportDetailRes_data'
      example:
        data:
          id: 0
    PatentReportDetailRes_data:
      type: object
      properties:
        id:
          type: integer
      example:
        id: 0
    Trend1Res_data:
      type: object
      properties:
        year:
          type: string
        num:
          type: integer
      example:
        year: year
        num: 0
    Trend2Res_data:
      type: object
      properties:
        year:
          type: string
        authorization_num:
          type: integer
        apply_num:
          type: integer
        proportion:
          type: number
          format: float
      example:
        proportion: 1.4658129
        year: year
        apply_num: 6
        authorization_num: 0
    ApplicantRes_data:
      type: object
      properties:
        applicant:
          type: string
        num:
          type: integer
      example:
        num: 0
        applicant: applicant
    AreaRes_data:
      type: object
      properties:
        year:
          type: string
        area:
          type: string
        num:
          type: integer
      example:
        area: area
        year: year
        num: 0
    TypeRes_data:
      type: object
      properties:
        type:
          type: string
        num:
          type: integer
      example:
        num: 0
        type: type
x-original-swagger-version: "2.0"

